CREATE DATABASE BANKING_SYSTEM;
USE BANKING_SYSTEM;

CREATE TABLE USER (
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE ACCOUNTS(
	ACCOUNT_NO BIGINT PRIMARY KEY,
	FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    BALANCE DECIMAL(10,2) NOT NULL,
    PIN VARCHAR(4) NOT NULL,
    UNIQUE (EMAIL),
    FOREIGN KEY (EMAIL) REFERENCES USER(EMAIL)
    );